volumes:
  app-vol:
  node-modules-vol:
  postgres-vol:

networks:
  - app-network
services:
  base: &base
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node-modules-vol:/home/node/app/node_modules
    networks:
      - app-network

  app:
    <<: *base
    container_name: app
    env_file:
      - ./.env
    ports:
      - 3003:3003
      - 9229:9229
    command: yarn dev

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 10s
      retries: 5

  specs:
    <<: *base
    command: yarn test
    env_file:
      - ./.env
    environment:
      NODE_ENV: local
